name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      location:
        required: true
        default: 'japanwest'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: test
            webworker: 1
            sqldb: GP_S_Gen5_1
          - environment: prod
            webworker: 2
            sqldb: GP_S_Gen5_2
    environment: ${{ matrix.environment }}
    env:
      resource_group: ${{ secrets.DEPLOY_PREFIX }}-${{ matrix.environment }}-rg
      prefix: ${{ secrets.DEPLOY_PREFIX }}-${{ matrix.environment }}
    steps:

    - name: Checkout source
      uses: actions/checkout@v2

    - name: Azure Login with Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create resource group if not exists
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.resource_group }} --location ${{ github.event.inputs.location }} --tags environment=${{matrix.environment}}

    - name: Deployment resource manager template
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.resource_group }}
        deploymentName: GHA_ARM_DEPLOY_${{github.run_number}}
        template: ./source/arm/armtemplate.json
        parameters: prefix=${{ env.prefix }} location=${{github.event.inputs.location}} webserverInstanceCount=${{matrix.webworker}} sqlServerlessSku=${{matrix.sqldb}} sqlUsername=${{env.prefix}} sqlPassword=${{secrets.AZURE_SQLDB_PASSWORD}} 


