name: Deploy Azure Resources

on:
  workflow_dispatch:
    inputs:
      location:
        required: true
        default: 'japanwest'

env:
  resource_group: ${{ github.event.inputs.prefix }}-rg

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v2

    - name: Azure Login with Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create resource group if not exists
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.resource_group }} --location ${{ github.event.inputs.location }}

    - name: Deployment resource manager template
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ env.resource_group }}
        template: ./source/arm/armtemplate.json
        parameters: prefix=${{secrets.DEPLOY_PREFIX}} location=${{github.event.inputs.location}} sqlUsername=${{secrets.DEPLOY_PREFIX}} sqlPassword=${{secrets.AZURE_SQLDB_PASSWORD}}
