name: Deploy ASP.NET Core web application

on:
  push:
    branches: 
      - master 
    paths: 
      - 'source/DemoApps/**'
  pull_request:
    branches:
      - master 
    paths: 
      - 'source/DemoApps/**'

env:
  app_src_dir: "source/DemoApps"
  app_package: ${{github.run_id}}.zip
  app_artifact_name: myapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.app_src_dir}}

    - name: Build ASP.NET Core application
      run: dotnet build --no-restore
      working-directory: ${{env.app_src_dir}}

    - name: Pulish ASP.NET Core application
      run: dotnet publish -o ./publish
      working-directory: ${{env.app_src_dir}}
    
    - name: Zip published artifacts
      run: |
        cd ./publish
        zip -r ../${{ env.app_package }} .
      working-directory: ${{env.app_src_dir}}
    
    - name: Upload app artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.app_artifact_name }}
        path: ${{ env.app_src_dir }}/${{ env.app_package }}

  deploy:
    needs: [ 'build' ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:

    - name: Download Application Artifact
      uses: actions/download-artifact@v2
      with: 
        name: ${{ env.app_artifact_name }}

    - name: Check Artifact
      run: ls -la

    - name: Azure Login with Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy zip to Azure App service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.TARGET_WEBAPP }}
        package: ${{ env.app_package }}

    - name: Logout
      run: az logout

