name: Deploy ASP.NET Core web application to Azure 

on:
  push:
    branches: [ master, deploy-actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/DemoApps
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pulish ASP.NET
      run: dotnet publish -o ./publish

    - name: Archive Content
      run: zip -r "./publish/${GITHUB_RUN_ID}.zip" ./publish/*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: source/DemoApps/publish/*.zip
