name: Deploy ASP.NET Core web application to Azure 

on:
  push:
    branches: [ master, deploy-actions ]
  pull_request:
    branches: [ master ]

env:
  artifact_name: myapp
  app_package: ${GITHUB_RUN_ID}.zip
  appservice_name: ainaba-demo1130

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/DemoApps
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pulish ASP.NET Core
      run: |
        dotnet publish -o ./publish
        cd ./publish
        zip -r ../${{ env.app_package }} .
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: source/DemoApps/${{ env.app_package }}

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with: 
        name: ${{ env.artifact_name }}

    - name: Check Artifact
      run: ls -la

    - name: Azure Login with Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy zip to Azure App service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.appservice_name }}
        package: ${{ env.app_package }}